### ISSUE TITLE
how does SNPGenie deal with invariant sites?

### ISSUE THREAD

**Issue by mufernando** [chasewnelson/SNPGenie#18]
Should I output invariant sites to my VCF or does it assume all sites are genotyped?

**Comment by singing-scientist** [comment]
Hey Murillo! Thanks for the question. No need to output invariant sites; SNPGenie assumes a typical VCF style, where only sites with variants are included. Let me know if that helps!

**Comment by mufernando** [comment]
Hi Chase,

Thanks for your reply. I think this can be problematic in some settings, given that it is possible not all sites have enough coverage to be genotyped. This can bias the statistic dramatically, specially in poorly covered regions, because you will divide by the window or gene size when in fact you could only survey a fraction of it. Dealing with missing data is crucial to get accurate pi estimates, but probably does not matter much to get piN/piS.

**Comment by singing-scientist** [comment]
I think you're absolutely right. In fact, that's one reason the site-by-site file is given: certainly, researchers should report mean π considering only those sites that have been successfully analyzed! Unfortunately, most VCFs do not include data for every site — which is understandable, e.g., considering the gargantuan size a human chromosome 1 file would consume. If you _do_ know that a certain number of sites should not be considered, one way to adjust is to 'manually' take the mean π over such sites: (sum of individual pi values at sites with appropriate coverage) / (total number of sites with appropriate coverage). Another option is to exclude them from the input (for example, not including those positions in the GTF, for CDS, or else the reference). Let me know if that helps!
