### ISSUE TITLE
sliding window error with new version compared to old version.

### ISSUE THREAD

**Issue by mschoup** [chasewnelson/SNPGenie#19]
Hi Chase

I'm very happy with SNPGenie and that you wrote in a way that has minimal requirements.  
I have encountered an anomaly when using the current version compared to an old one I used previously.

The sliding window result file looks like this with the current version:
file	product	first_site	first_codon	last_site	last_codon	sum_nonsyn_diffs	sum_syn_diffs	sum_nonsyn_sites	sum_syn_sites	piN	piS	piN/piS	piN_vs_ref	piS_vs_ref	piN/piS_vs_ref
WGS572_S13.vcf	ORF	1	ATG	150	AGG	0	0	0	0	*	*	*	*	*	*
WGS572_S13.vcf	ORF	4	AGC	153	AAG	0	0	0	0	*	*	*	*	*	*
WGS572_S13.vcf	ORF	7	ACA	156	ACT	0	0	0	0	*	*	*	*	*	*
WGS572_S13.vcf	ORF	10	AAT	159	TCC	0	0	0	0	*	*	*	*	*	*
WGS572_S13.vcf	ORF	13	CCT	162	GAG	0	0	0	0	*	*	*	*	*	*

The sliding window result file looks like this with the old version:
file	product	first_site	first_codon	last_site	last_codon	sum_nonsyn_diffs	sum_syn_diffs	sum_nonsyn_sites	sum_syn_sites	piN	piS	piN/piS	piN_vs_ref	piS_vs_ref	piN/piS_vs_ref
WGS572_S13.vcf	ORF	1	ATG	150	AGG	0	0.0228922932049934	111.5	38.5	0	0.000594605018311517	0	0	0.000300779220779221	0
WGS572_S13.vcf	ORF	4	AGC	153	AAG	0	0.0228922932049934	111.166666666667	38.8333333333333	0	0.000589501112574938	0	0	0.000298197424892704	0
WGS572_S13.vcf	ORF	7	ACA	156	ACT	0	0.0228922932049934	110.5	39.5	0	0.000579551726708694	0	0	0.000293164556962025	0

I am running this command:
snpgenie.pl --vcfformat=2 --snpreport=WGS572_S13.vcf --fastafile=WGS572_S13.consensus-map.fasta --minfreq=0.01 --slidingwindow=50 --gtffile=SNPGenie_orf.gff3

I have attached the files.
[SNPGenie-error.zip](https://github.com/chasewnelson/SNPGenie/files/3311810/SNPGenie-error.zip)

Am I missing something obvious?

Best,
Martin

**Comment by singing-scientist** [comment]
Thanks very much for using SNPGenie, Martin @mschoup, and apologies for the embarrassing bug. All values were reported as UNDEFINED (*) because I forgot to update expected new column names, which were implemented in an update, within the sliding window subroutine. That has now been fixed; please pull/download the new version and let me know if it works for you.

**Comment by mschoup** [comment]
I have just downloaded the new version and it is works.
Thanks for the swift solution!

Martin
