### ISSUE TITLE
Hello, I am trying to run snpgenie_wthin_group.pl after installing Parallel::ForkManager (with -force option) and get the error message:  MacBookPro:SNPGenie-master julia$ perl snpgenie_within_group.pl --fasta_file_name=compl_cons_ORF --gtf_file_name=GGS.gtf Can't locate Parallel/ForkManager.pm in @INC (@INC contains: /Library/Perl/5.16/darwin-thread-multi-2level /Library/Perl/5.16 /Network/Library/Perl/5.16/darwin-thread-multi-2level /Network/Library/Perl/5.16 /Library/Perl/Updates/5.16.2/darwin-thread-multi-2level /Library/Perl/Updates/5.16.2 /System/Library/Perl/5.16/darwin-thread-multi-2level /System/Library/Perl/5.16 /System/Library/Perl/Extras/5.16/darwin-thread-multi-2level /System/Library/Perl/Extras/5.16 .) at snpgenie_within_group.pl line 62.  BEGIN failed--compilation aborted at snpgenie_within_group.pl line 62.    Do you have any idea what I can do to fix it? Thanks!!!

### ISSUE THREAD

**Issue by jhillung** [chasewnelson/SNPGenie#26]

**Comment by singing-scientist** [comment]
Greetings! Unfortunately, I do not yet have sufficient details to answer. Did you use CPAN to install ForkManager?

**Comment by jhillung** [comment]
Hi, yes I used CPAN, but I had a error and had to use -force option as suggestion of the CPAN. Then it was apparently installed. Thanks!

________________________________
Von: Chase W. Nelson <notifications@github.com>
Gesendet: Donnerstag, 9. Januar 2020 21:11
An: chasewnelson/SNPGenie <SNPGenie@noreply.github.com>
Cc: jhillung <juliahillung@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [chasewnelson/SNPGenie] Hello, I am trying to run snpgenie_wthin_group.pl after installing Parallel::ForkManager (with -force option) and get the error message: MacBookPro:SNPGenie-master julia$ perl snpgenie_within_group.pl --fasta_file_name=comp...


Greetings! Unfortunately, I do not yet have sufficient details to answer. Did you use CPAN to install ForkManager?

**Comment by singing-scientist** [comment]
I am very glad to hear that it worked out! Thanks for using SNPGenie :-)
