### ISSUE TITLE
Invalid FASTA file

### ISSUE THREAD

**Issue by kloetzl** [chasewnelson/SNPGenie#3]
Call me nitpicky, but your [example FASTA file](https://github.com/hugheslab/snpgenie/blob/master/EXAMPLE_files/REFERENCE_EXAMPLE.fasta) is invalid.

```
> FASTA Reference Sequence
```

The space between `>` and `FASTA` makes the sequence have an _empty_ name, and I guess thats not what you want.

**Comment by singing-scientist** [comment]
Many thanks, again! I have fixed the FASTA description line.

**Comment by kloetzl** [comment]
:+1:
