### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by druvus** [chasewnelson/SNPGenie#31]
I would like to add SNPGenie to Bioconda for easy installation but to do that I would need a tagged release.

**Comment by singing-scientist** [comment]
Thank you so much for your generosity in suggesting the helpful change and for including SNPGenie in Bioconda! I have taken care of the commit and tagged a version. Please let me know if there is anything else I can do.

With gratitude,
Chase

**Comment by druvus** [comment]
thanks for the fast response! SNPGenie is now available for installation using Bioconda.
