### ISSUE TITLE
Watterson's theta and Tajima's D estimates

### ISSUE THREAD

**Issue by sqiu86** [chasewnelson/SNPGenie#47]
Hi Chase, thanks for the brilliant software. We are trying to get the Watterson's theta and Tajima's D estimates on the synonymous sites for our pooled sequence data. I wonder whether the software could provide these information? Thanks in advance!

**Comment by singing-scientist** [comment]
Greetings! I am sorry to say that these calculations are not built into the SNPGenie software, and unfortunately I do not have time to add this functionality right now (but I will add it to my list for a future version 2!).

However, in case it's helpful, I have uploaded the R script `Tajima_D.R` to this repository, which contains the function `Tajima.D()`. You provide it with the sequence length, number of segregating sites, and total nucleotide diversity (e.g., calculated from SNPGenie). For example, for *n*=1000 sequences with *S*=15 segregating sites and *π*=0.05, one would run it as follows:

`Tajima.D(1000, 15, 0.05)`

which produces:

```
D	sig.level
-2.142552	0.01
```

Details on calculating exact P-values are in his paper, if needed. However, I must emphasize that I have NOT tested this code extensively. (In fact, it would be a great help if you try it out and let me know if it produces the correct result for you!) Moreover, it is probably possible to many many well-tested functions for calculating Tajima's D in various R and Python libraries (but then again, maybe not?). 

Sorry I cannot provide better news, but hopefully this helps!

Best,
Chase

**Comment by sqiu86** [comment]
Hi Chase,

Thanks very much for the quick reply and the R script ! I'll definitely give it a try!

Suo

**Comment by singing-scientist** [comment]
No problem! Let me know. Also, I need to correct myself: n should be the number of sequences (i.e., sample size), not the number of sites. (This edit has been made above.)

**Comment by pascalangst** [comment]
Hi @singing-scientist 

Is there any news related to the calculation of theta or Tajima's D using SNPGenie? Can we calculate it based on any of the output files of SNPGenie?

Also, for `Tajima.D()`, how is the number of sequences to be understood for the within-pool analysis? Or, with other words: what is the number of sequences in the case of a pool-seq sample? Is it the number of haploid genomes pooled for sequencing?

Thank you in advance.
Pascal

**Comment by singing-scientist** [comment]
Hi @pascalangst ! Thanks so much. Unfortunately there is no new version of SNPGenie yet. You should be able to use the S and π reported by SNPGenie and simply use those values as input to the Tajima.D() script. Perhaps I've misunderstood?

Regarding number of sequences, that's a great question — there are probably as many ways of answering it as there are study designs. For example, are your data one deep-sequenced sample? Multiple samples? Multiple samples combined at known ratios? The answer will probably differ for each case. If you describe your data a little I may be able to provide some feedback!

Yours,
Chase

**Comment by pascalangst** [comment]
Hi Chase,

Thank you for coming back to me so quickly! There is no misunderstanding regarding S and π. This is clear to me. Regarding number of sequences, I can describe my data a bit more. I have population samples of pooled individuals, i.e., one sample consists out of 50 individuals that were pooled before sequencing.

Pascal

**Comment by singing-scientist** [comment]
Ah, perfect! If haploid, it seems clear 50 should be total number of sequences per sample; if diploid, 100. S is straightforward. For π, can use SNPGenie's estimate (fine approximation) or determine the exact number (of 50 or 100) sequences that has variant(s) and recalculate π that way. Let me know if makes sense!

**Comment by pascalangst** [comment]
That makes sense. Thank you, Chase.
Best wishes, 
Pascal.

**Comment by singing-scientist** [comment]
With pleasure! Best wishes for a great study :-)
