### ISSUE TITLE
All classified as synonymous

### ISSUE THREAD

**Issue by marotbone** [chasewnelson/SNPGenie#63]
Hi,

I'm using SNPGenie on bacterial data of pooled samples with very low frequent SNPs which I called with [lofreq](https://csb5.github.io/lofreq/). 

I am using SNPGenie Version: 2019.10.31 with the following command:
`snpgenie.pl --fastafile=PsymA.fasta --gtffile PsymA_cds.gtf --snpreport PsymA_recode.vcf --vcfformat=2`

In my opinion this seems to be the most appropriate option for my case.
All works fine so far, but when I check `site_results.txt` all the sites are classified as synonymous and some columns seem to be missing (e.g ref_nt and codon).

Here is a ZIP file with the input files and the generated output folder.
[PsymA_test.zip](https://github.com/chasewnelson/SNPGenie/files/9489036/PsymA_test.zip)

What could be the reason for this? 

Thanks.

Best,
Maro

**Comment by singing-scientist** [comment]
Greetings, Maro!

Thanks very much for using SNPGenie and for the question. Looking at your sites_results.txt file, indeed it is odd. I ran the data for myself, and the site_results.txt looks correct (or at least, not odd):

[SNPGenie_Results_CWN.zip](https://github.com/chasewnelson/SNPGenie/files/9507582/SNPGenie_Results_CWN.zip)

It is possible (likely) this is a bug from an older version. Can you download the latest SNPGenie from this repository and try it again?

Let me know!
Chase

**Comment by marotbone** [comment]
Hi Chase,

Thanks for the support.
The strange behavior was caused by the equal sign in the command to pass the fastafile. 
I am sorry for wasting your time.

Great tool, it seems to perfectly match our needs. Thank you!

Best,
Maro

**Comment by singing-scientist** [comment]
How odd! I'm glad the solution was simple. Please let me know if anything else comes up!

Many thanks,
Chase
