### ISSUE TITLE
Warning for coverage and nucleotide sums

### ISSUE THREAD

**Issue by shamavirani** [chasewnelson/SNPGenie#73]
Hi, 

Thanks for creating and maintaining this tool so well, it is much appreciated!

I'm running the within pool analysis using a multisample vcf and I'm getting the warning:
## the coverage (345.000) does not equal the nucleotide sum (1029.000).

and thus

## This should occur only when conflicting coverages have been reported.

However, I'm looking at the temp vcf and I don't see where that nucleotide sum is coming from. I've done a lot of troubleshooting and am now coming to you because I'm not sure what to do here. For info, this is happening for multiple samples at the same positions, however, this is not happening at all positions. I've emailed the vcf.

Thank you,
Shama

**Comment by singing-scientist** [comment]
Greetings @shamavirani and apologies for the holiday delay! I have received the vcf but in order for me to best pin down what's happening, I'd be grateful for a MRE (minimal reproducible example): a set of 1) vcf 2) fasta 3) gtf that can be quickly run to reproduce the issue. Without having seen your files, it's possible e.g., that your GTF contains multiple distinct CDS records (e.g. alternate transcripts) by the same name, but impossible to know. Let me know!

**Comment by shamavirani** [comment]
@singing-scientist sorry for that oversight, sent!

**Comment by shamavirani** [comment]
@singing-scientist I've resolved the issue, there were non-SNPs included in my vcf. Many thanks for the responsiveness and for this great tool.
