### ISSUE TITLE
problems with gtf file

### ISSUE THREAD

**Issue by chantisakee** [chasewnelson/SNPGenie#76]
Hi,

Thank you for your interesting and helpful tool!
I would like to work with rickettsia genome so i got the gtf file from NCBI. and i got tons of issue like this--

## SNPGenie terminated.

when i've fixed one then the other one comes up. Just wondering what do i have to do with the gtf file.. can i use it directly from the souce?

Thank you

**Comment by chantisakee** [comment]
[GCF_000008045.1_ASM804v1_genomic_CDS.gtf.zip](https://github.com/user-attachments/files/17038422/GCF_000008045.1_ASM804v1_genomic_CDS.gtf.zip)

**Comment by chantisakee** [comment]
the issue is solved now.

**Comment by singing-scientist** [comment]
@chantisakee glad to hear it! Let me know if anything else comes up.

Sincerely,
Chase
