### ISSUE TITLE
Empty output / wrong VCF file?

### ISSUE THREAD

**Issue by WardDeb** [chasewnelson/SNPGenie#8]
Hi,

I'm trying to run SNPgenie on a couple of sequences that I've mapped from different samples. I've called the SNPs using freebayes, and produced the GTF file using prodigal. I needed to tinker a little bit with the files, but I think at this point they should be ok to use. However when I run SNPgenie with following command:

`snpgenie.pl --vcfformat=4 --snpreport=vcffile.vcf --fastafile=fastafile.fna --gtffile=gtffile.gtf
`

The Program runs, and I get immediattely following output:
```
################################################################################
##                                                                            ##
##                             SNPGenie Initiated!                            ##
##                                                                            ##
################################################################################

  ###############################  LICENSE:  #################################
  ##            SNPGenie Copyright (C) 2015-18 Chase W. Nelson              ##
  ##            This program comes with ABSOLUTELY NO WARRANTY;             ##
  ##     This is free software, and you are welcome to redistribute it      ##
  ##               under certain conditions; see LICENSE.txt.               ##
  ############################################################################

You have not selected a MIN. MINOR ALLELE FREQ. All variants in the SNP report(s) will be included.

Reading in FASTA file... COMPLETED.

Indexing sequence... COMPLETED.

################################################################################
##                      SNPGenie completed successfully.                      ##
##             Please find results in the SNPGenie_Results folder.            ##
################################################################################

```

However when I look into the results output, all the files are empty.. 
I'm a bit puzzled at what could be causing this, and I think the VCF file could be the problem? I've inserted the files in here for troubleshooting. 

Thanks in advance!

Warddeb

**Comment by singing-scientist** [comment]
Thanks very much for using SNPGenie, @WardDeb ! 

It appears to be failing because there is no HEADER in the VCF file (i.e., #CHROM<TAB>POS<TAB>ID<TAB>...). I have implemented a warning to alert the user when this is the case. Please let me know if you still encounter any problems when the header is included.

Best,
Chase

**Comment by WardDeb** [comment]
Thanks @cwnelson88, 

Rerunning with header seems to have fixed the problem. Output looks as expected now.

Thanks for the quick response!
